# NumPy functions

### NumPy Array Shape


In [26]:
import numpy as np
arr = np.array([[11,33,22], [55, 16, 27]])
arr1= np.array([11,20,32,49])

print(arr.shape)
print(arr1.shape)


(2, 3)
(4,)


### All in one example

In [27]:
array_example = np.array([  [[11,13,45,6],
                            [41, 15, 6, 7]],

                            [[21,5,79,6],
                            [34,66,9,1]],

                            [[33,61,4,21],
                            [1,23, 76, 87]],
                          
                            [[2,4,8,9],
                             [6,99,7,5]] ])
 
print('No of dimensions of the array:',array_example.ndim)     # .ndim for dimensions
print('Total no of elements of the array:',array_example.size) # .size for size
print('Shape of the array:',array_example.shape)                # .shape for shape

No of dimensions of the array: 3
Total no of elements of the array: 32
Shape of the array: (4, 2, 4)


## NumPy Array Reshaping

In [28]:
#Reshape from 1D to 2D
import numpy as np
arr1 = np.array([10, 23, 13, 54, 95, 6, 57, 80, 92, 15, 17, 12])
newarr1 = arr1.reshape(2,6)
arr2 = np.array(['V','a','i','s','h','n','a','v','i'])
newarr2 = arr2.reshape(3,3)
print(newarr1)
print(newarr2)

[[10 23 13 54 95  6]
 [57 80 92 15 17 12]]
[['V' 'a' 'i']
 ['s' 'h' 'n']
 ['a' 'v' 'i']]


In [29]:
#Reshape from 1d to 3d
import numpy as np
arr = np.array([10, 23, 13, 54, 95, 6, 57, 80, 92, 15, 17, 12])
newarr = arr.reshape(2, 3, 2)
print(newarr)

[[[10 23]
  [13 54]
  [95  6]]

 [[57 80]
  [92 15]
  [17 12]]]


In [30]:
#Multidimensional array into 1 dimensional
import numpy as np
arr = np.array([[1,2,3],[6,7,8]])
arr1 = arr.reshape(-1)
print(arr1)

[1 2 3 6 7 8]


## NumPy Searching and Sorting

In [31]:
# NumPy sorting
import numpy as np
arr1 = np.array([1,9,33,2,99,65,3,42])
arr2 = np.array(['vaishu','anjali','jojo','mani','abhs'])
arr3 = np.array([[22,3,49],[333,6,76]])

print(np.sort(arr1))

print(np.sort(arr2))

print(np.sort(arr3))



[ 1  2  3  9 33 42 65 99]
['abhs' 'anjali' 'jojo' 'mani' 'vaishu']
[[  3  22  49]
 [  6  76 333]]


In [32]:
# NumPy Searching
#where()
import numpy as np
arr1 = np.array([55,44,20,3,6,87,9,50,6,71])
x = np.where(arr1 == 6)
y = np.where(arr1%5 == 0)
z = np.where(arr1%5 == 1)
print(x)
print(y)
print(z)

    
#searchsorted() :

arr1 = np.array([68, 72, 84, 96])
x = np.searchsorted(arr1, 72)
print(x)
   
# Multiple values
arr2 = np.array([18, 44,63,90])
y = np.searchsorted(arr2, [44,90])
print(y)

(array([4, 8], dtype=int32),)
(array([0, 2, 7], dtype=int32),)
(array([4, 8, 9], dtype=int32),)
1
[1 3]


## Mean, Median, Mode

In [33]:
# Mean
import numpy as np
a = np.array([3,4,4,32,26,77,90])
b =  np.mean(a)
print("Mean of array {} is {}".format(a,b))

Mean of array [ 3  4  4 32 26 77 90] is 33.714285714285715


In [34]:
# Median
# For one value in the middle
import numpy as np
a = np.array([1,3,9,47,85,3,45,89,66,22,17])
print("Median of {} is {}".format(a, np.median(a)))

Median of [ 1  3  9 47 85  3 45 89 66 22 17] is 22.0


In [35]:
# Median
#For two values in the middle
import numpy as np
a = np.array([1,3,9,47,85,3,89,66,22,17])
print("Median of {} is {}".format(a, np.median(a)))

Median of [ 1  3  9 47 85  3 89 66 22 17] is 19.5


In [36]:
#Mode
from scipy import stats
a = [34,87,55,6,12,9,55,9,6,40,3,66,55,120]
print("Mode of {} is {}".format(a, stats.mode(a)))


Mode of [34, 87, 55, 6, 12, 9, 55, 9, 6, 40, 3, 66, 55, 120] is ModeResult(mode=array([55]), count=array([3]))


## Standard Deviation

In [37]:
import numpy
speed = [45,89,55,63,22,90]
x = numpy.std(speed)
print(x)
   
speed1 = [199,34,55,333,85,9933,3,551]
y = numpy.std(speed1)
print(y)

23.949019928914744
3230.1236213765874
