# NumPy Basics

### Creating a Basic Array

In [40]:
import numpy as np
arr1 = np.array([11,2,33,44,55])        #List is used to make array
arr2 = np.array(['a','e','i','o','u'])
arr3 = np.array(('a',100,'z',44))      #Tuple is used to make array
print(arr1)
print(arr2)
print(arr3)

[11  2 33 44 55]
['a' 'e' 'i' 'o' 'u']
['a' '100' 'z' '44']


In [41]:
print(type(arr3))                     #type of array c
print(type(arr2))                     #type of array b

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


Arrays using **np.zeros(), np.ones() and np.arange()**.

In [42]:
arr4 = np.zeros(7)
arr5 = np.ones(5)
arr6 = np.arange(4,9)                #specify start point and end point
arr7 = np.arange(14,24,2)            #specify start point, end point and step size
arr8 = np.arange(15)
print(arr4)
print(arr5)
print(arr6)
print(arr7)
print(arr8)

[0. 0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1.]
[4 5 6 7 8]
[14 16 18 20 22]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


## N-dimensional Array

In [43]:
# 2d dimensional array
import numpy as np
arr1=np.array([[12,13,44],[42,52,61]])
arr2=np.array([[11,2,13],[40,5,16],[17,18,9]])
arr3=np.array([['a','e','i'],['o','u','w']])
   
#creates a 3X3 array with all zeros
zeros=np.zeros((4,4))
   
#creates a 2X2 array with all ones
ones=np.ones((3,3),dtype='int64')  #specify the type with (dtype) parameter 
   
print(arr1)
print(arr2)
print(arr3)
print(zeros)
print(ones)

[[12 13 44]
 [42 52 61]]
[[11  2 13]
 [40  5 16]
 [17 18  9]]
[['a' 'e' 'i']
 ['o' 'u' 'w']]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1 1 1]
 [1 1 1]
 [1 1 1]]


In [44]:
# ndim
a = np.array(3)
b = np.array([4,55,6,1,0,2,33])
c = np.array([[4,6,8], [3,12,9], [5,66,11]])

print(a.ndim)
print(b.ndim)
print(c.ndim)

0
1
2


### Basic operations with Arrays

In [45]:
import numpy as np
arr1 = np.array([30,40,20,20,10])
arr2 = np.array([5,23,1,6,20])
c = arr1 + arr2
d = arr1 - arr2
e = arr1 / arr2

print(c)                     #addition
print(d)                     #subtraction
print(e)                     #division

print("Adding 2 to all elements:", c+2)
print("Subtracting 2 from all elements:", d-2)

[35 63 21 26 30]
[ 25  17  19  14 -10]
[ 6.          1.73913043 20.          3.33333333  0.5       ]
Adding 2 to all elements: [37 65 23 28 32]
Subtracting 2 from all elements: [ 23  15  17  12 -12]


## Array Indexing and Slicing

### Array Indexing

In [46]:
import numpy as np
arr1 = np.array([12,2,33,44])
arr2 = np.array([23,1,14,30])
arr3 = np.array(['V','a','i','s','h','n','a','v','i'])
arr4 = np.array([[51,2,33], [12,3,77]])

print(arr1[0]) # prints first element
print(arr1[-1]) # prints last element
print(arr2[2]) # prints third element
print(arr3[0]) # prints first element
print(arr4[1][1]) #prints 3
print(arr4[1,1]) # Or you can use this type

12
44
14
V
3
3


### Array Slicing

In [47]:

import numpy as np
arr1=np.array(['V','a','i','s','h','n','a','v','i'])
arr2=np.array([11,22,33,44,55,66,77,88,99])
   
# 2-D Slicing
arr3=np.array([[10,11,21,22,23], [34,43,45,66,99]])
   
print(arr1[:2]) # default is taken as 0
print(arr1[0:3])
print(arr1[5:]) # taken till the end
print(arr1[::2])
   
print(arr2[-4:-1])
print(arr2[::2]) # step size as 2
   
# 2-D Slicing
print(arr3[1,1:4])
print(arr3[0:2, 2])
print(arr3[0:2, 1:4])

['V' 'a']
['V' 'a' 'i']
['n' 'a' 'v' 'i']
['V' 'i' 'h' 'a' 'i']
[66 77 88]
[11 33 55 77 99]
[43 45 66]
[21 45]
[[11 21 22]
 [43 45 66]]


### All in one example

In [48]:
import numpy as np
data = np.array([11, 22, 30])
print(data[1])
print(data[0:2])
print(data[1:])
print(data[-2:])

22
[11 22]
[22 30]
[22 30]
